# Static Traefik config
# Official documentation: https://doc.traefik.io/traefik/reference/static-configuration/file/

api:
  insecure: true
  dashboard: true

log:
  # level: "DEBUG"
  level: "ERROR"

accessLog:
  fields:
    names:
      StartUTC: drop

metrics:
  prometheus:
    entryPoint: "metrics"
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    exposedByDefault: false
    network: "traefik-proxy"
    watch: true
  file:
    filename: '/etc/traefik/dynamic/dynamic.yml'
    watch: true

entryPoints:
  metrics:
    address: ":8082"

  web:
    address: ":80"

  websecure:
    address: ":443"

  mongo:
    address: ":27017"